import type { Metadata } from "next";
import {Roboto} from "next/font/google"
import "./globals.css";
import { NavBar } from "./components/Navbar";


const roboto = Roboto({weight: ["400", "700"], subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Fitness Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <NavBar/>
        <main className="py-20 max-w-6xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
